Added shebang to setenv.

diff --git a/setenv b/setenv
--- a/setenv
+++ b/setenv
@@ -1,3 +1,5 @@
+#!/usr/bin/env -S sh -c "echo >&2 \"Error: You are running this script instead of sourcing it. Make sure to use it as 'source setenv' or '. setenv', otherwise its settings won't take effect.\"; exit 1"
+
 export OPP_REPL_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 export PATH="$OPP_REPL_ROOT:$PATH"
 export PYTHONPATH="$OPP_REPL_ROOT/python:$PYTHONPATH"
